import { z } from "zod";
import { validateFormData } from "./formContract.js";

const RawScenarioSchema = z.object({
  title: z.string().min(1),
  expected: z.enum(["success", "validation-error"]).optional(),
  reason: z.string().optional(),
  data: z.object({
    name: z.coerce.string(),
    email: z.coerce.string(),
    phone: z.coerce.string(),
    city: z.coerce.string(),
    message: z.coerce.string()
  })
});

const defaultScenarios = [
  {
    title: "Valid form submission",
    data: {
      name: "Niharika",
      email: "niharika@example.com",
      phone: "9876543210",
      city: "Guwahati",
      message: "This is a valid message for testing."
    }
  },
  {
    title: "All fields are empty",
    data: {
      name: "",
      email: "",
      phone: "",
      city: "",
      message: ""
    }
  },
  {
    title: "Invalid email format",
    data: {
      name: "Riya",
      email: "riyaexample.com",
      phone: "9876543210",
      city: "Delhi",
      message: "This message has a valid length."
    }
  },
  {
    title: "Invalid phone number",
    data: {
      name: "Aman",
      email: "aman@example.com",
      phone: "12345",
      city: "Mumbai",
      message: "This message has a valid length."
    }
  },
  {
    title: "Name starts with lowercase letter",
    data: {
      name: "john",
      email: "john@example.com",
      phone: "9876543210",
      city: "Pune",
      message: "This message has a valid length."
    }
  },
  {
    title: "City contains numbers",
    data: {
      name: "Sara",
      email: "sara@example.com",
      phone: "9876543210",
      city: "City123",
      message: "This message has a valid length."
    }
  },
  {
    title: "Message is too short",
    data: {
      name: "Kiran",
      email: "kiran@example.com",
      phone: "9876543210",
      city: "Jaipur",
      message: "Hi"
    }
  },
  {
    title: "SQL injection attempt in message",
    data: {
      name: "Testuser",
      email: "sql.test@example.com",
      phone: "9876543210",
      city: "Kolkata",
      message: "' OR '1'='1' -- ; DROP TABLE users;"
    }
  },
  {
    title: "Script injection attempt in message",
    data: {
      name: "Meera",
      email: "meera@example.com",
      phone: "9876543210",
      city: "Chennai",
      message: "<script>alert('xss')</script>"
    }
  },
  {
    title: "Edge-valid values",
    data: {
      name: "Zo",
      email: "zo@test.in",
      phone: "9999999999",
      city: "Goa",
      message: "Exactly ten"
    }
  }
];

function sanitizeScenarioData(data) {
  return {
    name: String(data.name ?? ""),
    email: String(data.email ?? ""),
    phone: String(data.phone ?? ""),
    city: String(data.city ?? ""),
    message: String(data.message ?? "")
  };
}

export function normalizeScenarios(raw, _formContract, desiredCount = 10) {
  const rawList = Array.isArray(raw) ? raw : raw?.scenarios;

  if (!Array.isArray(rawList)) {
    throw new Error("Gemini response did not contain a scenarios array.");
  }

  const candidates = [...rawList, ...defaultScenarios];
  const normalized = [];
  const seen = new Set();

  for (const candidate of candidates) {
    const parsed = RawScenarioSchema.safeParse(candidate);

    if (!parsed.success) {
      continue;
    }

    const data = sanitizeScenarioData(parsed.data.data);
    const expectedErrors = validateFormData(data);
    const expected =
      Object.keys(expectedErrors).length === 0
        ? "success"
        : "validation-error";

    const title = parsed.data.title.trim().replace(/\s+/g, " ").slice(0, 120);
    const uniqueKey = JSON.stringify({ data, expected });

    if (seen.has(uniqueKey)) {
      continue;
    }

    seen.add(uniqueKey);

    normalized.push({
      id: `TC-${String(normalized.length + 1).padStart(3, "0")}`,
      title,
      expected,
      data,
      expectedErrors,
      reason:
        parsed.data.reason ||
        "Scenario generated by Gemini and validated against the local form contract."
    });

    if (normalized.length >= desiredCount) {
      break;
    }
  }

  if (normalized.length === 0) {
    throw new Error("No valid test scenarios were generated.");
  }

  return normalized;
}